"use strict";

// STATUS.md — the one page a developer or a new AI session reads first.
// Deterministic: the same project state always renders the same bytes (no wall-clock time).

const { LABELS, STAGE_LABELS } = require("../derive/status.cjs");
const { nextActions, readySlices, OPEN_STAGES } = require("../next/actions.cjs");
const { escapeCell } = require("../model/tables.cjs");

const HORIZON_ORDER = { now: 0, next: 1, later: 2, backlog: 3 };
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const cell = (v) => escapeCell(v === undefined || v === null || v === "" ? "—" : v);
const table = (header, rows) => (rows.length ? [`| ${header.join(" | ")} |`, `|${header.map(() => "---").join("|")}|`, ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`)].join("\n") : "_None._");

function lastEventOf(model) {
  let last = null;
  const all = [...[...model.changes.values()].flatMap((c) => c.events || []), ...(model.approvals ? model.approvals.events : [])];
  for (const e of all) if (!last || Date.parse(e.when) > Date.parse(last.when)) last = e;
  return last;
}

function activity(e) {
  if (!e) return "—";
  return `${e.when.slice(0, 10)} · ${e.event} ${e.target}${e.note ? ` — ${e.note}` : ""}`;
}

function title(model, id) {
  const r = model.records.get(id);
  return r ? `${id} · ${r.title}` : id;
}

function renderBoard(model, status, drift = null) {
  const name = model.profile.project_name || model.code;
  const last = lastEventOf(model);
  const out = [];
  out.push(`# ${name} — Status`, "");
  out.push(`_Generated by \`royascaff index\` — do not edit. As of the last recorded event: ${last ? last.when : "none yet"}._`, "");

  // Next up
  out.push("## ▶ Next up", "");
  const actions = nextActions(model, status, drift);
  if (actions.length) {
    actions.slice(0, 5).forEach((a, i) => out.push(`${i + 1}. ${a.text}`));
    out.push("", '_Say "royascaff continue" to start the first item._');
  } else out.push("_Nothing active and no ready slice. Plan a feature: `royascaff new feature \"…\"`._");
  out.push("");

  // Features by horizon
  const features = [...model.features.values()].sort((a, b) => HORIZON_ORDER[a.horizon] - HORIZON_ORDER[b.horizon] || a.id.localeCompare(b.id));
  const featureRows = features.map((f) => {
    const d = status.features.get(f.id);
    const notes = [];
    if (d.openFixes.length) notes.push(`open fix: ${d.openFixes.join(", ")}`);
    const missing = d.requirements.filter((r) => status.requirements.get(r).missingEvidence);
    if (missing.length) notes.push(`⚠ no passing evidence: ${missing.join(", ")}`);
    if (drift && drift.featureChanged.has(f.id)) notes.push(`⚠️ changed since verified: ${drift.featureChanged.get(f.id).join(", ")}`);
    if (d.unprovenNfrs && d.unprovenNfrs.length) notes.push(`prove ${d.unprovenNfrs.join(", ")}`);
    // WP-C5 (P7): visual-bar lines a person did not pass on the feature's last looked-at change.
    const looked = [...model.changes.values()].filter((c) => c.slices.some((s) => model.features.get(f.id).slices.includes(s))).sort((a, b) => a.id.localeCompare(b.id)).map((c) => ({ c, gaps: require("../smoke.cjs").barGaps(c) })).filter((x) => x.gaps).pop();
    if (looked && looked.gaps.length) notes.push(`⚠ visual bar gaps: ${looked.gaps.join(", ")} (${looked.c.id})`);
    if (d.approval === "stale") notes.push("⚠ plan changed since approval");
    else if (d.approval === "none" && ["now", "next"].includes(f.horizon) && (d.requirementsTotal || d.slicesTotal) && ["outlined", "planned"].includes(d.state)) notes.push("plan not approved yet");
    return [cap(f.horizon), title(model, f.id), LABELS[d.state], cap(d.depth), `${d.slicesDone}/${d.slicesTotal}`, `${d.requirementsDone}/${d.requirementsTotal}`, notes.join("; ")];
  });
  out.push("## Features", "", table(["Horizon", "Feature", "State", "Depth", "Slices done", "Requirements done", "Notes"], featureRows), "");

  // Active work and fixes
  const open = [...model.changes.values()].filter((c) => OPEN_STAGES.includes(status.changes.get(c.id).stage)).sort((a, b) => a.id.localeCompare(b.id));
  const changeRow = (c, withKind) => {
    const d = status.changes.get(c.id);
    const stage = `${d.blocked ? "⛔ " : ""}${STAGE_LABELS[d.stage]}`;
    const base = [title(model, c.id)];
    if (withKind) base.push(c.kind || "—", c.affects.join(", "));
    else base.push(c.slices.join(", ") || "—");
    return [...base, stage, `${d.tasksDone}/${d.tasksTotal}`, activity(d.last)];
  };
  const isFix = (c) => ["bug", "polish"].includes(c.kind);
  out.push("## Active work", "", table(["Change", "Slice", "Stage", "Tasks done", "Last activity"], open.filter((c) => !isFix(c)).map((c) => changeRow(c, false))), "");
  out.push("## Fixes", "", table(["Change", "Kind", "Affects", "Stage", "Tasks done", "Last activity"], open.filter(isFix).map((c) => changeRow(c, true))), "");

  // Work outside the engine (git)
  if (drift && drift.git) {
    out.push("## ⚠ Work outside the engine", "");
    const loose = drift.uncommitted.filter((u) => !u.inTask);
    const knowledge = drift.uncommittedKnowledge || [];
    if (!drift.untrackedCommits.length && !loose.length && !knowledge.length) out.push("_None: git history and the working tree match the recorded work._", "");
    if (knowledge.length) {
      out.push(`⚠ Project knowledge not committed (${knowledge.length} file(s)): ${knowledge.slice(0, 6).map((k) => `\`${k.path}\``).join(", ")}${knowledge.length > 6 ? ", …" : ""}. Commit it with the task's code; tasks and changes cannot close before.`, "");
    }
    if (drift.untrackedCommits.length) {
      out.push("Commits no task or change covers:", "");
      out.push(table(["Commit", "Files", "Feature", "Record with"], drift.untrackedCommits.map((c) => [`${c.short} ${c.subject}`, c.files.join(", "), c.features.join(", "), `royascaff record ${c.short} --as bug|polish|refactor|chore "…"`])), "");
    }
    if (loose.length) {
      out.push("Uncommitted files outside every task (never discarded by the engine):", "");
      out.push(table(["File", "Git status", "Feature"], loose.map((u) => [u.path, u.code, u.features.join(", ")])), "");
    }
  }

  // Planned slices
  const deferredTo = new Map();
  if (model.is14) for (const d of require("../quality.cjs").deferrals(model)) deferredTo.set(d.slice, (deferredTo.get(d.slice) || 0) + 1);
  const planned = readySlices(model, status).map((s) => {
    const sl = model.slices.get(s.slice);
    const ref = drift && drift.refinement.get(s.slice);
    const refine = ref && ref.state === "needs" ? ` · ⚠ needs refinement: ${ref.changed.join(", ")}` : "";
    return [`${s.slice} · ${sl.title}`, s.feature, cap(s.horizon), sl.depends_on.join(", "), `${s.ready ? "yes" : s.waitsFor.length ? `waits for ${s.waitsFor.join(", ")}` : "waits for the Now features"}${refine}${deferredTo.has(s.slice) ? ` · ${deferredTo.get(s.slice)} deferred item(s)` : ""}${s.foundation ? " · foundation" : ""}`];
  });
  out.push("## Planned slices (not started)", "", table(["Slice", "Feature", "Horizon", "Depends on", "Ready?"], planned), "");

  // Recently closed
  const closed = [...model.changes.values()]
    .filter((c) => status.changes.get(c.id).stage === "closed")
    .map((c) => ({ c, when: status.changes.get(c.id).last ? status.changes.get(c.id).last.when : "" }))
    .sort((a, b) => b.when.localeCompare(a.when) || a.c.id.localeCompare(b.c.id))
    .slice(0, 5)
    .map(({ c, when }) => [title(model, c.id), c.slice || c.affects.join(", "), when ? when.slice(0, 10) : "—"]);
  out.push("## Recently closed", "", table(["Change", "Slice / affects", "Closed"], closed), "");

  // Health
  const errors = model.issues.filter((i) => i.severity === "error");
  const warnings = model.issues.filter((i) => i.severity === "warning");
  out.push("## Health", "");
  out.push(`- Validation: ${errors.length} errors · ${warnings.length} warnings (run \`royascaff validate\` for details)`);
  const shown = [...errors, ...warnings].slice(0, 10);
  for (const i of shown) out.push(`  - ${i.severity === "error" ? "✗" : "!"} ${i.message}`);
  if (errors.length + warnings.length > shown.length) out.push(`  - … and ${errors.length + warnings.length - shown.length} more`);
  if (model.approvals) {
    const a = model.approvals;
    const d = a.discovery;
    const p = a.project;
    const proj = p.state === "approved" ? `approved by ${p.by} (${p.when.slice(0, 10)})` : p.state === "stale" ? `⚠ changed since ${p.by} approved it` : "not approved yet";
    out.push(`- Discovery: ${d.questions} question(s), ${d.open.length + d.openByFeature.length} open · ${d.assumptions.length} assumption(s) · project ${proj}`);
    const c = a.coverage;
    if (c.exists) out.push(`- Brief: ${c.covered} of ${c.sources.length} demand(s) covered · ${c.outOfScope} out of scope${c.uncovered.length ? ` · ⚠ ${c.uncovered.length} not covered yet` : ""}${c.unquoted.length ? ` · ${c.unquoted.length} list item(s) of the request not quoted` : ""}`);
  }
  if (model.is14) {
    const { healthOf, healthLines } = require("./health.cjs");
    out.push(...healthLines(healthOf(model, status)));
  }
  out.push(`- Records: ${model.records.size} · features ${model.features.size} · slices ${model.slices.size} · changes ${model.changes.size} · tasks ${model.tasks.size}`);
  out.push("");
  const fs = require("fs");
  const path = require("path");
  const links = ["PLAYBOOK.md", "GLOSSARY.md"].filter((d) => fs.existsSync(path.join(model.root, d)));
  if (links.length) out.push(`_Help: ${links.map((d) => `[${d.replace(".md", "")}](${d})`).join(" · ")}_`, "");
  return out.join("\n");
}

module.exports = { renderBoard };
