"use strict";

// `index` (writes STATUS.md, root pointer, summary blocks) and the read-only views
// `status`, `tasks`, `trace`, `log`.

const fs = require("fs");
const path = require("path");
const { buildModel } = require("../model/graph.cjs");
const { deriveStatus, LABELS, STAGE_LABELS } = require("../derive/status.cjs");
const { renderBoard } = require("../views/board.cjs");
const { refreshSummaries } = require("../views/summary.cjs");
const { nextActions } = require("../next/actions.cjs");
const { findProject, listMarkdown } = require("../project.cjs");
const { computeDrift } = require("../derive/drift.cjs");

const POINTER_MARK = "<!-- royascaff:pointer -->";

function load(start) {
  const project = findProject(start);
  const model = buildModel(start);
  const status = deriveStatus(model);
  return { project, model, status };
}

function writeIfChanged(file, content) {
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return false;
  fs.writeFileSync(file, content);
  return true;
}

function indexCommand(start) {
  const first = load(start);
  const summaries = refreshSummaries(first.project.projectDir, listMarkdown(first.project).filter((f) => f.rel !== "STATUS.md"), first.model, first.status);
  const { project, model, status } = summaries.length ? load(start) : first;
  const board = renderBoard(model, status, computeDrift(model, status));
  const statusFile = path.join(project.projectDir, "STATUS.md");
  const boardChanged = writeIfChanged(statusFile, board);
  let pointer = null;
  if (project.layout === "project-folder") {
    const rootFile = path.join(project.repo, "STATUS.md");
    const own = !fs.existsSync(rootFile) || fs.readFileSync(rootFile, "utf8").includes(POINTER_MARK);
    if (own) {
      writeIfChanged(rootFile, `# Status\n\nThe status board of this project is [project/STATUS.md](project/STATUS.md), generated by \`royascaff index\`.\n\n${POINTER_MARK}\n`);
      pointer = "STATUS.md";
    }
  }
  return { status_file: path.relative(project.repo, statusFile), board_changed: boardChanged, root_pointer: pointer, summaries_updated: summaries, board };
}

function statusCommand(start) {
  const { model, status } = load(start);
  const features = [...model.features.values()].map((f) => ({ ...status.features.get(f.id), title: model.records.get(f.id).title }));
  const changes = [...model.changes.values()].map((c) => ({ ...status.changes.get(c.id), kind: c.kind, slice: c.slice, slices: c.slices, affects: c.affects, title: c.title }));
  const drift = computeDrift(model, status);
  return {
    next: nextActions(model, status, drift),
    features: features.map((f) => ({ ...f, changedSinceVerified: drift.featureChanged.get(f.id) || [] })),
    changes,
    outside: { git: drift.git, untrackedCommits: drift.untrackedCommits, uncommitted: drift.uncommitted.filter((u) => !u.inTask) },
    issues: model.issues,
  };
}

function tasksCommand(start, opts = {}) {
  const { model, status } = load(start);
  const featureOfChange = (c) => {
    if (c.slice && model.slices.get(c.slice)) return model.slices.get(c.slice).feature;
    for (const a of c.affects) {
      if (model.features.has(a)) return a;
      const r = model.records.get(a);
      const f = r && r.relations.find((x) => x.type === "feature" || x.type === "satisfies");
      if (f && model.features.has(f.to)) return f.to;
    }
    return null;
  };
  const rows = [];
  for (const change of [...model.changes.values()].sort((a, b) => a.id.localeCompare(b.id))) {
    if (opts.change && change.id !== opts.change) continue;
    const feature = featureOfChange(change);
    if (opts.feature && feature !== opts.feature) continue;
    for (const tid of change.tasks) {
      const t = status.tasks.get(tid);
      if (opts.open && t.state === "done") continue;
      rows.push({ id: tid, title: model.records.get(tid).title, change: change.id, feature, state: t.state, depends_on: model.tasks.get(tid).depends_on, last: t.last ? { when: t.last.when, event: t.last.event, by: t.last.by, note: t.last.note } : null });
    }
  }
  const text = rows.length
    ? rows.map((r) => `${r.state.padEnd(7)} ${r.id} · ${r.title}  (${r.change}${r.feature ? `, ${r.feature}` : ""})${r.depends_on.length ? ` · after ${r.depends_on.join(", ")}` : ""}${r.last && r.last.note ? ` — ${r.last.note}` : ""}`).join("\n")
    : "No tasks match.";
  return { tasks: rows, text };
}

function traceCommand(start, id) {
  const { model, status } = load(start);
  const rec = model.records.get(id);
  if (!rec) throw new Error(`${id} not found`);
  const lab = (x) => {
    const d = status.features.get(x) || status.requirements.get(x) || status.slices.get(x);
    if (d) return LABELS[d.state];
    const c = status.changes.get(x);
    return c ? STAGE_LABELS[c.stage] : "";
  };
  const t = (x) => `${x} · ${model.records.get(x) ? model.records.get(x).title : "(missing)"}`;
  const lines = [];
  const traceRequirement = (rid, indent) => {
    const pad = " ".repeat(indent);
    const r = model.records.get(rid);
    const d = status.requirements.get(rid);
    lines.push(`${pad}${t(rid)}   ${lab(rid)}`);
    for (const sid of d.slices) {
      const sl = model.slices.get(sid);
      lines.push(`${pad}  slice    ${t(sid)}   ${lab(sid)}`);
      if (sl.change) {
        const c = model.changes.get(sl.change);
        const cs = status.changes.get(sl.change);
        lines.push(`${pad}    change ${t(sl.change)}   ${STAGE_LABELS[cs.stage]} · tasks ${cs.tasksDone}/${cs.tasksTotal}`);
        const tasks = c.tasks.filter((tid) => model.records.get(tid).relations.some((x) => x.type === "inputs" && x.to === rid));
        for (const tid of tasks) lines.push(`${pad}      task ${t(tid)}   ${status.tasks.get(tid).state}`);
      }
    }
    if (!d.slices.length) lines.push(`${pad}  slice    none — not planned yet`);
    const tests = [...new Set([...r.relations.filter((x) => x.type === "verified_by").map((x) => x.to), ...(model.incoming.get(rid) || []).filter((x) => x.type === "verifies").map((x) => x.from)])];
    for (const test of tests) lines.push(`${pad}  test     ${t(test)}`);
    for (const e of d.evidence) {
      const ev = model.evidence.get(e);
      lines.push(`${pad}  evidence ${t(e)}   ${ev.result}${ev.change ? ` (${ev.change})` : ""}`);
    }
    if (!d.evidence.length) lines.push(`${pad}  evidence none yet`);
    const code = (model.incoming.get(rid) || []).filter((x) => ["realizes", "implements"].includes(x.type) || (x.type === "satisfies" && model.records.get(x.from)?.kind === "component")).map((x) => x.from);
    const realizedBy = r.relations.filter((x) => x.type === "realized_by").map((x) => x.to);
    for (const cmp of [...new Set([...code, ...realizedBy])]) {
      const c = model.records.get(cmp);
      lines.push(`${pad}  code     ${t(cmp)}${c && c.fields.Code ? ` → ${c.fields.Code}` : ""}`);
    }
    for (const fix of d.openFixes) lines.push(`${pad}  open fix ${t(fix)}   ${STAGE_LABELS[status.changes.get(fix).stage]}`);
  };
  if (model.features.has(id)) {
    const d = status.features.get(id);
    const outcome = rec.relations.find((x) => x.type === "outcome" || x.type === "supports");
    lines.push(`${t(id)}   ${LABELS[d.state]} · slices ${d.slicesDone}/${d.slicesTotal} · requirements ${d.requirementsDone}/${d.requirementsTotal}`);
    if (outcome) lines.push(`  outcome  ${t(outcome.to)}`);
    for (const rid of d.requirements) traceRequirement(rid, 2);
    if (!d.requirements.length) lines.push("  no requirements yet");
  } else if (status.requirements.has(id)) {
    const f = rec.relations.find((x) => x.type === "feature" || x.type === "satisfies");
    if (f) lines.push(`feature  ${t(f.to)}   ${lab(f.to)}`);
    traceRequirement(id, 0);
  } else {
    throw new Error(`trace works on features (CAP-) and requirements; use \`royascaff show ${id}\``);
  }
  return { id, text: lines.join("\n") };
}

function parseSince(since) {
  if (!since) return null;
  const m = String(since).match(/^(\d+)d$/);
  if (m) return Date.now() - Number(m[1]) * 86400000;
  const t = Date.parse(since);
  if (Number.isNaN(t)) throw new Error(`--since must be like 7d or 2026-09-20`);
  return t;
}

function logCommand(start, opts = {}) {
  const { model } = load(start);
  const since = parseSince(opts.since);
  const events = [];
  for (const c of model.changes.values()) {
    if (opts.change && c.id !== opts.change) continue;
    for (const e of c.events || []) if (since === null || Date.parse(e.when) >= since) events.push({ change: c.id, ...e });
  }
  events.sort((a, b) => Date.parse(b.when) - Date.parse(a.when) || a.change.localeCompare(b.change) || b.index - a.index);
  const limited = opts.limit ? events.slice(0, Number(opts.limit)) : events;
  const text = limited.length ? limited.map((e) => `${e.when}  ${e.change.padEnd(12)} ${e.event.padEnd(16)} ${e.target}  by ${e.by}${e.note ? ` — ${e.note}` : ""}`).join("\n") : "No events.";
  return { events: limited.map(({ index, line, ...e }) => e), text };
}

module.exports = { indexCommand, statusCommand, tasksCommand, traceCommand, logCommand, POINTER_MARK };
